Extract Snapshots Collection
jsf9k/cyhy-feeds pull request #53
Opened 2024-05-14 16:17 UTC by DJensen94

Add the snapshots collection and its query to the array of collections to extract

#  #

## 🗣 Description ##
Add the snapshots collection and its query to the array of collections to extract.
## 💭 Motivation and context ##

We need to pull the snapshots data so the Crossfeed application can recreate the VS report for stakeholders.

## 🧪 Testing ##
Tested query locally 
## ✅ Pre-approval checklist ##

- [X] This PR has an informative and human-readable title.
- [X] Changes are limited to a single goal - *eschew scope creep!*
- [X] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [X] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

2024-05-14 16:21 UTC, jsf9k requested changes

2024-05-14 16:21 UTC, jsf9k commented on aws_jobs/cyhy-data-extract.py
> +        "snapshots": {
Move the `snapshots` section below the `requests` section to keep things alphabetized.

2024-05-14 16:46 UTC, jsf9k commented on aws_jobs/cyhy-data-extract.py
> +        "snapshots": {
Done in commit 816a23a.

2024-05-14 16:47 UTC, jsf9k approved these changes

2024-05-14 16:58 UTC, dav3r approved these changes
Approved, though I have questions about what exactly this means, but I will talk with @climber-girl about them:
> We need to pull the snapshots data so the Crossfeed application can recreate the VS report for stakeholders.

Do you only want snapshot data going forward (i.e. after this PR is merged and deployed) or do you also want the ~1.2 million snapshot documents that already exist in the CyHy DB?  If the latter, then we will have to coordinate on that outside of this PR.

2024-05-14 17:16 UTC, DJensen94 commented
> Approved, though I have questions about what exactly this means, but I will talk with @climber-girl about them:
> 
> > We need to pull the snapshots data so the Crossfeed application can recreate the VS report for stakeholders.
> 
> Do you only want snapshot data going forward (i.e. after this PR is merged and deployed) or do you also want the ~1.2 million snapshot documents that already exist in the CyHy DB? If the latter, then we will have to coordinate on that outside of this PR.

We only want snapshots going forward.

2024-05-14 17:19 UTC, dav3r commented
> > Do you only want snapshot data going forward (i.e. after this PR is merged and deployed) or do you also want the ~1.2 million snapshot documents that already exist in the CyHy DB? If the latter, then we will have to coordinate on that outside of this PR.
> 
> We only want snapshots going forward.

Excellent, thanks for confirming! 👍

2024-05-14 20:04 UTC, DJensen94 commented
@dav3r I am not authorized to merge, is there anything else that is required before this can be merged?

2024-05-14 20:10 UTC, dav3r commented
> @dav3r I am not authorized to merge, is there anything else that is required before this can be merged?

I think all that's left is for you to check any remaining checkboxes in the PR description that apply (e.g. the one about reading the CONTRIBUTING doc), then remove any checkboxes or sections (e.g. the Pre-merge checklist) that don't apply.

Note that I put a couple of post-merge tasks in, one for your team and one for my team.

2024-05-15 14:12 UTC, DJensen94 commented
@dav3r All checks complete, and we have reached out to AE so they are aware a new collection is on the way

2024-05-15 15:44 UTC, jsf9k commented
Is the "All future TODOs are captured in issues, which are referenced
in code comments." checkbox needed here or can that just be deleted?  I didn't see any TODOs in this PR.

2024-05-15 17:35 UTC, dav3r commented
> @dav3r All checks complete, and we have reached out to AE so they are aware a new collection is on the way

@DJensen94 I just got an email from @jessiebeals stating:
> Please do not deploy any changes if they will be automatically pushed to the AE with the daily extracts; we will need to coordinate with ME prior to pushing new data into their environment.

We are going to hold off on merging this PR until I get the green light from the AE side, mainly to ensure that this code is not unintentionally deployed before they are ready.  I'm adding the `blocked` label to this PR for that purpose.

2024-06-05 13:39 UTC, dav3r commented
@DJensen94 Do you have any updates on this?  I have not heard anything.

2024-08-07 15:10 UTC, dav3r commented
@DJensen94 @climber-girl @jessiebeals - Are there any updates on this effort?

2024-10-07 13:59 UTC, dav3r commented
@DJensen94 @climber-girl @jessiebeals - Is this PR still needed?

2025-01-21 18:35 UTC, dav3r commented
This PR has been idle for a long time, so I'm closing it.  Feel free to re-open and comment if needed.

2025-03-27 18:39 UTC, felddy commented
Reopening as there is renewed interest in getting snapshots to the [XFD](https://github.com/cisagov/XFD) via the AE.

2025-04-07 18:45 UTC, jsf9k commented
@cisagov/vm-dev - In [cisagov/skeleton-python-library](https://github.com/cisagov/skeleton-python-library) we only test versions of Python that are not EOL.  (Currently this is Python 3.9 and later.)  Should we do the same here?

At a minimum I think we _have to_ remove testing for Python 3.6 and 3.7 since those versions are unavailable in GitHub runners.

2025-04-07 19:45 UTC, dv4harr10 approved these changes

2025-04-07 19:50 UTC, jsf9k commented
The folks who voiced renewed interest in this pull request have now said that they no longer require it, so I am closing it.

It is worth mentioning that it would be better to skeletonize this repository rather than include the commits that I created (89dba76, 7f20f47, 2b4277c, and 52a3979).

2025-04-07 19:50 UTC, closed without merging